### ISSUE TITLE
Submit to canvas

### ISSUE THREAD

**Issue by jaymegordo** [UBC-MDS/NiceNumber#14]
In the textbox provided on Canvas for the Milestone 1 assignment you must include:

1. The URL of your public project’s repo
2. The URL to a release on your project repo named v0.1.0
3. A link to your team work document that is accessible to the teaching team. Alternatively a copy of your team work document can be pasted there.

**Comment by jaymegordo** [comment]
Make sure we re-read all the milestone goals and ensure we have completed all of them!

**Comment by camharris22** [comment]
Milestone goals completed and submitted to Canvas!
